# Generated by Django 5.1.1 on 2024-10-14 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits_app', '0002_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
