# Generated by Django 5.1.1 on 2024-10-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits_app', '0003_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='product', to='fruits_app.category'),
        ),
    ]
