# Generated by Django 5.1.1 on 2024-10-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits_app', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
